### ISSUE TITLE
restrictive access to port 8080

### ISSUE THREAD

**Issue by magic-54** [taranis-ai/taranis-ai#424]
Installed Taranis AI on a remote server, but I can't set a firewall on 8080 and allow access only from certain IP addresses
sudo ufw allow from XXXXXXXXX to any port 8080
ufw deny 8080
or
https://github.com/chaifeng/ufw-docker

non of these is not working and can have worldwide access to the panel

**Comment by b3n4kh** [comment]
This could be achieved by either putting a nginx reverse proxy limiting the access to these IPs in front of taranis or building taranis gui yourself with these restrictions in-place.

Add to compose.yml
 ```
  nginx-proxy:
    image: nginx:latest
    ports:
      - "${TARANIS_PORT:-8080}:80"
    depends_on:
      - gui
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    deploy:
      restart_policy:
        condition: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```

remove or comment out the "ports:" section of gui!

nginx-proxy.conf
```
http {
    server {
        listen 80;

        location / {
            allow 10.0.0.0/8;
            deny all;

            proxy_pass http://gui:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
```

And you should be good to go
